name: "bump-version"
description: "version bump for NodeJS project"
inputs:
  base-directory:
    description: 'the base directory to run version bump'
    required: false
  version:
    description: 'which version level needed to bump version, eg. npm version patch'
    required: false
    default: 'patch'
runs:
  using: 'node20'
  main: 'dist/index.js'