name: "nodejs-setup"
description: "Setup action for NodeJS project"
inputs:
  package-name: 
    description: 'package name'
    required: true
  nodejs-version: 
    description: 'nodejs version'
    required: true

  install-registry-url:
    description: 'install registry url'
    required: true
  install-registry-email:
    description: 'install registry email'
    required: true
  install-registry-username:
    description: 'install registry username'
    required: true
  install-registry-password:
    description: 'install registry password'
    required: true
  install-registry-token-credential:
    description: 'install registry token credential'
    required: false

  publish-registry-email:
    description: 'publish registry email'
    required: true
  publish-registry-username:
    description: 'publish registry username'
    required: true
  publish-registry-password:
    description: 'publish registry password'
    required: true
  publish-registry-token-credential:
    description: 'publish registry token credential'
    required: false

  pax-ssh-host:
    description: 'ssh host for pax'
    required: false
  pax-ssh-port:
    description: 'ssh port for pax'
    required: false
  pax-ssh-credential:
    description: 'ssh credential'
    required: false
  pax-remote-workspace:
    description:  'remote workspace path'
    required: false

  always-use-npm-install:
    description: 'always use npm install'
    required: false
    default: 'false'
  exit-if-folder-not-clean:
    description: 'exit workflow if git folder not clean'
    required: false
  debug:
    description: 'enable print command'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{github.action_path}}/..
        npm install
        cd ${{github.action_path}}
        node setup.js
      shell: bash
      env:
        INPUT_PACKAGE-NAME: ${{ inputs.package-name }}
        INPUT_NODEJS-VERSION: ${{ inputs.nodejs-version }}
        INPUT_PUBLISH-REGISTRY-EMAIL: ${{ inputs.publish-registry-email }}
        INPUT_PUBLISH-REGISTRY-USERNAME: ${{ inputs.publish-registry-username }}
        INPUT_PUBLISH-REGISTRY-PASSWORD: ${{ inputs.publish-registry-password }}
        INPUT_INSTALL-REGISTRY-URL: ${{ inputs.install-registry-url }}
        INPUT_INSTALL-REGISTRY-EMAIL: ${{ inputs.install-registry-email }}
        INPUT_INSTALL-REGISTRY-USERNAME: ${{ inputs.install-registry-username }}
        INPUT_INSTALL-REGISTRY-PASSWORD: ${{ inputs.install-registry-password }}
        INPUT_ALWAYS-USE-NPM-INSTALL: ${{ inputs.always-use-npm-install }}
        INPUT_EXIT-IF-FOLDER-NOT-CLEAN: ${{ inputs.exit-if-folder-not-clean }}
        DEBUG: ${{ inputs.debug }}
